export const COUNTRIES = [
  { flag: "🇦🇫", name: "Afganistán", dialCode: "+93" },
  { flag: "🇦🇱", name: "Albania", dialCode: "+355" },
  { flag: "🇩🇿", name: "Argelia", dialCode: "+213" },
  { flag: "🇦🇩", name: "Andorra", dialCode: "+376" },
  { flag: "🇦🇴", name: "Angola", dialCode: "+244" },
  { flag: "🇦🇬", name: "Antigua y Barbuda", dialCode: "+1268" },
  { flag: "🇦🇷", name: "Argentina", dialCode: "+54" },
  { flag: "🇦🇲", name: "Armenia", dialCode: "+374" },
  { flag: "🇦🇺", name: "Australia", dialCode: "+61" },
  { flag: "🇦🇹", name: "Austria", dialCode: "+43" },
  { flag: "🇦🇿", name: "Azerbaiyán", dialCode: "+994" },
  { flag: "🇧🇸", name: "Bahamas", dialCode: "+1242" },
  { flag: "🇧🇭", name: "Baréin", dialCode: "+973" },
  { flag: "🇧🇩", name: "Bangladés", dialCode: "+880" },
  { flag: "🇧🇧", name: "Barbados", dialCode: "+1246" },
  { flag: "🇧🇾", name: "Bielorrusia", dialCode: "+375" },
  { flag: "🇧🇪", name: "Bélgica", dialCode: "+32" },
  { flag: "🇧🇿", name: "Belice", dialCode: "+501" },
  { flag: "🇧🇯", name: "Benín", dialCode: "+229" },
  { flag: "🇧🇹", name: "Bután", dialCode: "+975" },
  { flag: "🇧🇴", name: "Bolivia", dialCode: "+591" },
  { flag: "🇧🇦", name: "Bosnia y Herzegovina", dialCode: "+387" },
  { flag: "🇧🇼", name: "Botsuana", dialCode: "+267" },
  { flag: "🇧🇷", name: "Brasil", dialCode: "+55" },
  { flag: "🇧🇳", name: "Brunéi", dialCode: "+673" },
  { flag: "🇧🇬", name: "Bulgaria", dialCode: "+359" },
  { flag: "🇧🇫", name: "Burkina Faso", dialCode: "+226" },
  { flag: "🇧🇮", name: "Burundi", dialCode: "+257" },
  { flag: "🇨🇻", name: "Cabo Verde", dialCode: "+238" },
  { flag: "🇰🇭", name: "Camboya", dialCode: "+855" },
  { flag: "🇨🇲", name: "Camerún", dialCode: "+237" },
  { flag: "🇨🇦", name: "Canadá", dialCode: "+1" },
  { flag: "🇶🇦", name: "Catar", dialCode: "+974" },
  { flag: "🇨🇫", name: "República Centroafricana", dialCode: "+236" },
  { flag: "🇹🇩", name: "Chad", dialCode: "+235" },
  { flag: "🇨🇱", name: "Chile", dialCode: "+56" },
  { flag: "🇨🇳", name: "China", dialCode: "+86" },
  { flag: "🇨🇾", name: "Chipre", dialCode: "+357" },
  { flag: "🇻🇦", name: "Ciudad del Vaticano", dialCode: "+379" },
  { flag: "🇨🇴", name: "Colombia", dialCode: "+57" },
  { flag: "🇰🇲", name: "Comoras", dialCode: "+269" },
  { flag: "🇨🇬", name: "Congo", dialCode: "+242" },
  { flag: "🇨🇩", name: "Congo (RD)", dialCode: "+243" },
  { flag: "🇰🇵", name: "Corea del Norte", dialCode: "+850" },
  { flag: "🇰🇷", name: "Corea del Sur", dialCode: "+82" },
  { flag: "🇨🇮", name: "Costa de Marfil", dialCode: "+225" },
  { flag: "🇨🇷", name: "Costa Rica", dialCode: "+506" },
  { flag: "🇭🇷", name: "Croacia", dialCode: "+385" },
  { flag: "🇨🇺", name: "Cuba", dialCode: "+53" },
  { flag: "🇩🇰", name: "Dinamarca", dialCode: "+45" },
  { flag: "🇩🇯", name: "Yibuti", dialCode: "+253" },
  { flag: "🇩🇲", name: "Dominica", dialCode: "+1767" },
  { flag: "🇩🇴", name: "República Dominicana", dialCode: "+1809" },
  { flag: "🇪🇨", name: "Ecuador", dialCode: "+593" },
  { flag: "🇪🇬", name: "Egipto", dialCode: "+20" },
  { flag: "🇸🇻", name: "El Salvador", dialCode: "+503" },
  { flag: "🇦🇪", name: "Emiratos Árabes Unidos", dialCode: "+971" },
  { flag: "🇬🇶", name: "Guinea Ecuatorial", dialCode: "+240" },
  { flag: "🇪🇷", name: "Eritrea", dialCode: "+291" },
  { flag: "🇸🇰", name: "Eslovaquia", dialCode: "+421" },
  { flag: "🇸🇮", name: "Eslovenia", dialCode: "+386" },
  { flag: "🇪🇸", name: "España", dialCode: "+34" },
  { flag: "🇺🇸", name: "Estados Unidos", dialCode: "+1" },
  { flag: "🇪🇪", name: "Estonia", dialCode: "+372" },
  { flag: "🇸🇿", name: "Esuatini", dialCode: "+268" },
  { flag: "🇪🇹", name: "Etiopía", dialCode: "+251" },
  { flag: "🇵🇭", name: "Filipinas", dialCode: "+63" },
  { flag: "🇫🇮", name: "Finlandia", dialCode: "+358" },
  { flag: "🇫🇯", name: "Fiyi", dialCode: "+679" },
  { flag: "🇫🇷", name: "Francia", dialCode: "+33" },
  { flag: "🇬🇦", name: "Gabón", dialCode: "+241" },
  { flag: "🇬🇲", name: "Gambia", dialCode: "+220" },
  { flag: "🇬🇪", name: "Georgia", dialCode: "+995" },
  { flag: "🇬🇭", name: "Ghana", dialCode: "+233" },
  { flag: "🇬🇩", name: "Granada", dialCode: "+1473" },
  { flag: "🇬🇷", name: "Grecia", dialCode: "+30" },
  { flag: "🇬🇹", name: "Guatemala", dialCode: "+502" },
  { flag: "🇬🇳", name: "Guinea", dialCode: "+224" },
  { flag: "🇬🇼", name: "Guinea-Bisáu", dialCode: "+245" },
  { flag: "🇬🇾", name: "Guyana", dialCode: "+592" },
  { flag: "🇭🇹", name: "Haití", dialCode: "+509" },
  { flag: "🇭🇳", name: "Honduras", dialCode: "+504" },
  { flag: "🇭🇺", name: "Hungría", dialCode: "+36" },
  { flag: "🇮🇳", name: "India", dialCode: "+91" },
  { flag: "🇮🇩", name: "Indonesia", dialCode: "+62" },
  { flag: "🇮🇶", name: "Irak", dialCode: "+964" },
  { flag: "🇮🇷", name: "Irán", dialCode: "+98" },
  { flag: "🇮🇪", name: "Irlanda", dialCode: "+353" },
  { flag: "🇮🇸", name: "Islandia", dialCode: "+354" },
  { flag: "🇨🇰", name: "Islas Cook", dialCode: "+682" },
  { flag: "🇲🇭", name: "Islas Marshall", dialCode: "+692" },
  { flag: "🇸🇧", name: "Islas Salomón", dialCode: "+677" },
  { flag: "🇮🇱", name: "Israel", dialCode: "+972" },
  { flag: "🇮🇹", name: "Italia", dialCode: "+39" },
  { flag: "🇯🇲", name: "Jamaica", dialCode: "+1876" },
  { flag: "🇯🇵", name: "Japón", dialCode: "+81" },
  { flag: "🇯🇴", name: "Jordania", dialCode: "+962" },
  { flag: "🇰🇿", name: "Kazajistán", dialCode: "+7" },
  { flag: "🇰🇪", name: "Kenia", dialCode: "+254" },
  { flag: "🇰🇬", name: "Kirguistán", dialCode: "+996" },
  { flag: "🇰🇮", name: "Kiribati", dialCode: "+686" },
  { flag: "🇽🇰", name: "Kosovo", dialCode: "+383" },
  { flag: "🇰🇼", name: "Kuwait", dialCode: "+965" },
  { flag: "🇱🇦", name: "Laos", dialCode: "+856" },
  { flag: "🇱🇸", name: "Lesoto", dialCode: "+266" },
  { flag: "🇱🇻", name: "Letonia", dialCode: "+371" },
  { flag: "🇱🇧", name: "Líbano", dialCode: "+961" },
  { flag: "🇱🇷", name: "Liberia", dialCode: "+231" },
  { flag: "🇱🇾", name: "Libia", dialCode: "+218" },
  { flag: "🇱🇮", name: "Liechtenstein", dialCode: "+423" },
  { flag: "🇱🇹", name: "Lituania", dialCode: "+370" },
  { flag: "🇱🇺", name: "Luxemburgo", dialCode: "+352" },
  { flag: "🇲🇬", name: "Madagascar", dialCode: "+261" },
  { flag: "🇲🇾", name: "Malasia", dialCode: "+60" },
  { flag: "🇲🇼", name: "Malaui", dialCode: "+265" },
  { flag: "🇲🇻", name: "Maldivas", dialCode: "+960" },
  { flag: "🇲🇱", name: "Malí", dialCode: "+223" },
  { flag: "🇲🇹", name: "Malta", dialCode: "+356" },
  { flag: "🇲🇦", name: "Marruecos", dialCode: "+212" },
  { flag: "🇲🇺", name: "Mauricio", dialCode: "+230" },
  { flag: "🇲🇷", name: "Mauritania", dialCode: "+222" },
  { flag: "🇲🇽", name: "México", dialCode: "+52" },
  { flag: "🇫🇲", name: "Micronesia", dialCode: "+691" },
  { flag: "🇲🇩", name: "Moldavia", dialCode: "+373" },
  { flag: "🇲🇨", name: "Mónaco", dialCode: "+377" },
  { flag: "🇲🇳", name: "Mongolia", dialCode: "+976" },
  { flag: "🇲🇪", name: "Montenegro", dialCode: "+382" },
  { flag: "🇲🇿", name: "Mozambique", dialCode: "+258" },
  { flag: "🇲🇲", name: "Myanmar", dialCode: "+95" },
  { flag: "🇳🇦", name: "Namibia", dialCode: "+264" },
  { flag: "🇳🇷", name: "Nauru", dialCode: "+674" },
  { flag: "🇳🇵", name: "Nepal", dialCode: "+977" },
  { flag: "🇳🇮", name: "Nicaragua", dialCode: "+505" },
  { flag: "🇳🇪", name: "Níger", dialCode: "+227" },
  { flag: "🇳🇬", name: "Nigeria", dialCode: "+234" },
  { flag: "🇳🇴", name: "Noruega", dialCode: "+47" },
  { flag: "🇳🇿", name: "Nueva Zelanda", dialCode: "+64" },
  { flag: "🇴🇲", name: "Omán", dialCode: "+968" },
  { flag: "🇵🇰", name: "Pakistán", dialCode: "+92" },
  { flag: "🇵🇼", name: "Palaos", dialCode: "+680" },
  { flag: "🇵🇸", name: "Palestina", dialCode: "+970" },
  { flag: "🇵🇦", name: "Panamá", dialCode: "+507" },
  { flag: "🇵🇬", name: "Papúa Nueva Guinea", dialCode: "+675" },
  { flag: "🇵🇾", name: "Paraguay", dialCode: "+595" },
  { flag: "🇳🇱", name: "Países Bajos", dialCode: "+31" },
  { flag: "🇵🇪", name: "Perú", dialCode: "+51" },
  { flag: "🇵🇱", name: "Polonia", dialCode: "+48" },
  { flag: "🇵🇹", name: "Portugal", dialCode: "+351" },
  { flag: "🇬🇧", name: "Reino Unido", dialCode: "+44" },
  { flag: "🇨🇿", name: "República Checa", dialCode: "+420" },
  { flag: "🇷🇴", name: "Rumanía", dialCode: "+40" },
  { flag: "🇷🇺", name: "Rusia", dialCode: "+7" },
  { flag: "🇷🇼", name: "Ruanda", dialCode: "+250" },
  { flag: "🇰🇳", name: "San Cristóbal y Nieves", dialCode: "+1869" },
  { flag: "🇸🇲", name: "San Marino", dialCode: "+378" },
  { flag: "🇻🇨", name: "San Vicente y las Granadinas", dialCode: "+1784" },
  { flag: "🇱🇨", name: "Santa Lucía", dialCode: "+1758" },
  { flag: "🇸🇹", name: "Santo Tomé y Príncipe", dialCode: "+239" },
  { flag: "🇸🇦", name: "Arabia Saudí", dialCode: "+966" },
  { flag: "🇸🇳", name: "Senegal", dialCode: "+221" },
  { flag: "🇷🇸", name: "Serbia", dialCode: "+381" },
  { flag: "🇸🇨", name: "Seychelles", dialCode: "+248" },
  { flag: "🇸🇱", name: "Sierra Leona", dialCode: "+232" },
  { flag: "🇸🇬", name: "Singapur", dialCode: "+65" },
  { flag: "🇸🇴", name: "Somalia", dialCode: "+252" },
  { flag: "🇱🇰", name: "Sri Lanka", dialCode: "+94" },
  { flag: "🇿🇦", name: "Sudáfrica", dialCode: "+27" },
  { flag: "🇸🇩", name: "Sudán", dialCode: "+249" },
  { flag: "🇸🇸", name: "Sudán del Sur", dialCode: "+211" },
  { flag: "🇸🇪", name: "Suecia", dialCode: "+46" },
  { flag: "🇨🇭", name: "Suiza", dialCode: "+41" },
  { flag: "🇸🇷", name: "Surinam", dialCode: "+597" },
  { flag: "🇸🇾", name: "Siria", dialCode: "+963" },
  { flag: "🇹🇯", name: "Tayikistán", dialCode: "+992" },
  { flag: "🇹🇼", name: "Taiwán", dialCode: "+886" },
  { flag: "🇹🇿", name: "Tanzania", dialCode: "+255" },
  { flag: "🇹🇭", name: "Tailandia", dialCode: "+66" },
  { flag: "🇹🇱", name: "Timor Oriental", dialCode: "+670" },
  { flag: "🇹🇬", name: "Togo", dialCode: "+228" },
  { flag: "🇹🇴", name: "Tonga", dialCode: "+676" },
  { flag: "🇹🇹", name: "Trinidad y Tobago", dialCode: "+1868" },
  { flag: "🇹🇳", name: "Túnez", dialCode: "+216" },
  { flag: "🇹🇲", name: "Turkmenistán", dialCode: "+993" },
  { flag: "🇹🇷", name: "Turquía", dialCode: "+90" },
  { flag: "🇹🇻", name: "Tuvalu", dialCode: "+688" },
  { flag: "🇺🇦", name: "Ucrania", dialCode: "+380" },
  { flag: "🇺🇬", name: "Uganda", dialCode: "+256" },
  { flag: "🇺🇾", name: "Uruguay", dialCode: "+598" },
  { flag: "🇺🇿", name: "Uzbekistán", dialCode: "+998" },
  { flag: "🇻🇺", name: "Vanuatu", dialCode: "+678" },
  { flag: "🇻🇪", name: "Venezuela", dialCode: "+58" },
  { flag: "🇻🇳", name: "Vietnam", dialCode: "+84" },
  { flag: "🇼🇸", name: "Samoa", dialCode: "+685" },
  { flag: "🇾🇪", name: "Yemen", dialCode: "+967" },
  { flag: "🇿🇲", name: "Zambia", dialCode: "+260" },
  { flag: "🇿🇼", name: "Zimbabue", dialCode: "+263" },
];

export const DEFAULT_COUNTRY = COUNTRIES.find(
  (c) => c.dialCode === "+34" && c.name === "España"
);
